version: "3"
services:
  service:
    build:
      context: app
      network: host
    expose:
      - "8000"
    volumes:
      - ./app/static:/var/www/:rw
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./configs:/etc/nginx/conf.d
      - ./app/static:/var/www
    ports:
      - "80:80"
    depends_on:
      - service
  