version: "3"
services:
  service:
    build:
      context: app
    expose:
      - "8000"
    volumes:
      - ./app/static:/var/www/:rw
      - ./app/logs:/opt/app/logs/:rw
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:16
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./app/static:/var/www/static:ro
    ports:
      - "80:80"
    depends_on:
      - service
    networks:
      - app_network

networks:
  app_network:
    driver: bridge