# Generated by Django 4.2.11 on 2024-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='personproject',
            index=models.Index(fields=['person'], name='person_proj_person__a0921a_idx'),
        ),
        migrations.AddIndex(
            model_name='personproject',
            index=models.Index(fields=['project'], name='person_proj_project_393402_idx'),
        ),
    ]
